/**
 * ExecutionEngine.js - Runs the plan generated by the CoreAgent
 */

// Import all the specialized "worker" agents
import ProjectAgent from '../ProjectAgent';
import FinancialAgent from '../FinancialAgent';
import EstimateInvoiceAgent from '../EstimateInvoiceAgent';
import DocumentAgent from '../DocumentAgent';

class ExecutionEngine {
  constructor() {
    // A registry of all available agents
    this.agents = {
      ProjectAgent: new ProjectAgent(),
      FinancialAgent: new FinancialAgent(),
      EstimateInvoiceAgent: new EstimateInvoiceAgent(),
      DocumentAgent: new DocumentAgent(),
    };
  }

  /**
   * Executes a plan and streams the response.
   * @param {object} planObject - The plan from CoreAgent, e.g., { reasoning: '...', plan: [...] }.
   * @param {string} originalUserMessage - The original full user message.
   * @param {object} context - The full dynamic context.
   * @param {object} conversationState - The current conversation state.
   * @param {array} conversationHistory - The conversation history (messages).
   * @param {function} onChunk - Callback for streaming text chunks.
   * @param {function} onComplete - Callback for the final structured response.
   * @param {function} onError - Callback for errors.
   */
  async executePlan(planObject, originalUserMessage, context, conversationState, conversationHistory, onChunk, onComplete, onError) {
    const { plan } = planObject;
    console.log('🚀 [Executor] Starting execution of plan:', plan);

    if (!plan || plan.length === 0) {
      console.warn('🚀 [Executor] Received an empty plan. Nothing to execute.');
      if (onComplete) onComplete({
        text: "Is there anything else I can help with?",
        visualElements: [],
        actions: [],
        quickSuggestions: []
      });
      return;
    }

    // For now, we will focus on executing the FIRST step of the plan for simplicity.
    // A more advanced version could chain multiple steps.
    const step = plan[0];
    const agent = this.agents[step.agent];

    if (!agent) {
      const errorMessage = `Agent "${step.agent}" not found.`;
      console.error(`❌ [Executor] ${errorMessage}`);
      if (onError) onError(new Error(errorMessage));
      return;
    }

    try {
      // Replace FULL_MESSAGE placeholder with the actual original message
      const userInput = step.user_input === 'FULL_MESSAGE' ? originalUserMessage : step.user_input;

      // Delegate the task to the appropriate agent.
      // The agent itself will handle the streaming (onChunk, onComplete).
      console.log(`🚀 [Executor] Delegating to ${step.agent} for task: ${step.task}`);
      await agent.processStreaming(
        step.task,
        userInput,
        context,
        conversationState,
        conversationHistory,
        onChunk,
        onComplete,
        onError
      );
    } catch (error) {
      console.error(`❌ [Executor] Error during agent execution:`, error);
      if (onError) {
        onError(error);
      }
    }
  }
}

export const executePlan = (...args) => {
  const engine = new ExecutionEngine();
  return engine.executePlan(...args);
};
