/**
 * ExecutionEngine.js - Runs the plan generated by the CoreAgent
 *
 * MULTI-STEP EXECUTION WITH PROGRESSIVE UPDATES
 * - Executes ALL steps in a plan sequentially
 * - Streams progress for each step ("Creating project... ✓ Done!")
 * - Passes context from step N to step N+1
 * - Accumulates visual elements and actions from all steps
 */

// Import all the specialized "worker" agents
import ProjectAgent from '../ProjectAgent';
import FinancialAgent from '../FinancialAgent';
import EstimateInvoiceAgent from '../EstimateInvoiceAgent';
import DocumentAgent from '../DocumentAgent';
import WorkersSchedulingAgent from '../WorkersSchedulingAgent';
import SettingsConfigAgent from '../SettingsConfigAgent';
import logger from '../../../utils/logger';

class ExecutionEngine {
  constructor() {
    // A registry of all available agents
    this.agents = {
      ProjectAgent: new ProjectAgent(),
      FinancialAgent: new FinancialAgent(),
      EstimateInvoiceAgent: new EstimateInvoiceAgent(),
      DocumentAgent: new DocumentAgent(),
      WorkersSchedulingAgent: new WorkersSchedulingAgent(),
      SettingsConfigAgent: new SettingsConfigAgent(),
    };
  }

  /**
   * Builds context for next step based on previous step's results
   * @param {object} previousResult - Result from previous step execution
   * @param {object} baseContext - Original context
   * @returns {object} - Enhanced context for next step
   */
  buildStepContext(previousResult, baseContext) {
    return {
      ...baseContext,
      previousStepResult: {
        text: previousResult.text,
        visualElements: previousResult.visualElements,
        actions: previousResult.actions,
        // Extract any created entities for reference
        createdProject: previousResult.visualElements?.find(v => v.type === 'ProjectCard')?.data,
        createdEstimate: previousResult.visualElements?.find(v => v.type === 'EstimateCard')?.data,
        createdInvoice: previousResult.visualElements?.find(v => v.type === 'InvoiceCard')?.data,
      }
    };
  }

  /**
   * Get a friendly status message for the UI based on agent and task
   * Used for ChatGPT-style status indicators
   */
  getStatusMessage(agent, task) {
    const STATUS_MESSAGES = {
      // ==================== PROJECT AGENT ====================
      ProjectAgent: {
        start_project_creation: 'Setting up new project',
        continue_project_creation: 'Finishing project setup',
        update_project: 'Updating project details',
      },

      // ==================== WORKERS & SCHEDULING AGENT ====================
      WorkersSchedulingAgent: {
        // Worker management
        query_workers: 'Looking up worker info',
        manage_worker: 'Updating worker profile',
        assign_worker: 'Assigning worker to project',
        // Time tracking
        track_time: 'Pulling time records',
        edit_time_entry: 'Correcting time entry',
        // Schedule events (personal calendar)
        manage_schedule_event: 'Updating your calendar',
        retrieve_schedule_events: 'Checking your schedule',
        // Work schedules (worker assignments)
        manage_work_schedule: 'Scheduling crew assignments',
        // Reports & photos
        retrieve_photos: 'Loading job site photos',
        retrieve_daily_reports: 'Pulling daily reports',
        manage_daily_report: 'Saving daily report',
        // Payments
        query_worker_payment: 'Calculating worker pay',
        // Availability & PTO
        manage_availability: 'Checking worker availability',
        // Crew management
        manage_crew: 'Organizing crew',
        // Shift templates
        manage_shift_template: 'Loading shift templates',
        // Breaks
        manage_breaks: 'Recording break time',
        // Replacements
        find_replacement: 'Finding available workers',
        // Analytics
        analytics: 'Analyzing workforce data',
      },

      // ==================== ESTIMATE & INVOICE AGENT ====================
      EstimateInvoiceAgent: {
        create_estimate: 'Building your estimate',
        create_invoice: 'Generating invoice',
        update_estimate: 'Revising estimate',
        find_estimates: 'Searching estimates',
        find_invoices: 'Looking up invoices',
        send_estimate: 'Preparing to send estimate',
        create_project_from_estimate: 'Converting to project',
      },

      // ==================== FINANCIAL AGENT ====================
      FinancialAgent: {
        record_transaction: 'Recording transaction',
        answer_financial_question: 'Crunching the numbers',
        query_transactions: 'Pulling transactions',
        analyze_financials: 'Analyzing finances',
      },

      // ==================== DOCUMENT AGENT ====================
      DocumentAgent: {
        find_documents: 'Searching documents',
        find_project: 'Searching for project',
        update_project: 'Updating project details',
        delete_project: 'Removing project',
        answer_general_question: 'Thinking',
        add_estimate_to_project: 'Linking estimate to project',
        manage_estimate: 'Updating estimate status',
        manage_invoice: 'Processing invoice',
        manage_contract: 'Updating contract',
        search_documents: 'Searching all documents',
        list_contract_documents: 'Loading contracts',
        upload_contract_document: 'Uploading document',
        send_contract_document: 'Preparing to share contract',
      },

      // ==================== SETTINGS AGENT ====================
      SettingsConfigAgent: {
        query_settings: 'Loading your settings',
        manage_business_settings: 'Updating business info',
        manage_phase_templates: 'Configuring templates',
        manage_service_catalog: 'Updating service prices',
        manage_profit_margins: 'Adjusting profit margins',
        manage_subcontractor_quotes: 'Managing subcontractors',
        manage_invoice_template: 'Customizing invoice template',
      },
    };

    return STATUS_MESSAGES[agent]?.[task] || 'Working on it';
  }

  /**
   * Get a friendly action name for progress updates (used in multi-step streaming)
   */
  getStepActionName(step) {
    return this.getStatusMessage(step.agent, step.task);
  }

  /**
   * Executes a plan and streams the response.
   * NOW SUPPORTS MULTI-STEP EXECUTION WITH PROGRESSIVE UPDATES
   *
   * @param {object} planObject - The plan from CoreAgent, e.g., { reasoning: '...', plan: [...] }.
   * @param {string} originalUserMessage - The original full user message.
   * @param {object} context - The full dynamic context.
   * @param {object} conversationState - The current conversation state.
   * @param {array} conversationHistory - The conversation history (messages).
   * @param {function} onChunk - Callback for streaming text chunks.
   * @param {function} onComplete - Callback for the final structured response.
   * @param {function} onError - Callback for errors.
   * @param {function} onStatusChange - Callback for updating status message (e.g., "Creating project...")
   */
  async executePlan(planObject, originalUserMessage, context, conversationState, conversationHistory, onChunk, onComplete, onError, onStatusChange) {
    const { plan } = planObject;
    logger.debug('🚀 [Executor] Starting execution of plan:', plan);

    if (!plan || plan.length === 0) {
      logger.warn('🚀 [Executor] Received an empty plan. Nothing to execute.');
      if (onComplete) onComplete({
        text: "Is there anything else I can help with?",
        visualElements: [],
        actions: [],
      });
      return;
    }

    // SINGLE STEP - Use original fast path (no overhead)
    if (plan.length === 1) {
      const step = plan[0];
      const agent = this.agents[step.agent];

      if (!agent) {
        const errorMessage = `Agent "${step.agent}" not found.`;
        logger.error(`❌ [Executor] ${errorMessage}`);
        if (onError) onError(new Error(errorMessage));
        return;
      }

      try {
        const userInput = step.user_input === 'FULL_MESSAGE' ? originalUserMessage : step.user_input;

        // Update status message for this agent/task
        const statusMsg = this.getStatusMessage(step.agent, step.task);
        onStatusChange?.(statusMsg);

        logger.debug(`🚀 [Executor] Single step - delegating to ${step.agent} for task: ${step.task}`);
        await agent.processStreaming(
          step.task,
          userInput,
          context,
          conversationState,
          conversationHistory,
          onChunk,
          onComplete,
          onError
        );
      } catch (error) {
        logger.error(`❌ [Executor] Error during agent execution:`, error);
        if (onError) onError(error);
      }
      return;
    }

    // MULTI-STEP EXECUTION - PAUSE ON QUESTION (Manus-style)
    // If a step needs more info (asks question, no visualElements), pause and wait for user
    logger.debug(`🚀 [Executor] Multi-step execution: ${plan.length} steps`);

    // Accumulators for final response
    const allVisualElements = [];
    const allActions = [];
    let finalText = '';
    let lastNextSteps = null; // Track nextSteps from last step for handoffs
    let currentContext = context;

    for (let i = 0; i < plan.length; i++) {
      const step = plan[i];
      const isLastStep = i === plan.length - 1;
      const agent = this.agents[step.agent];

      if (!agent) {
        const errorMessage = `Agent "${step.agent}" not found.`;
        logger.error(`❌ [Executor] ${errorMessage}`);
        // Continue to next step instead of failing entirely
        continue;
      }

      try {
        const userInput = step.user_input === 'FULL_MESSAGE' ? originalUserMessage : step.user_input;
        const actionName = this.getStepActionName(step);

        // Update status message for this step
        onStatusChange?.(actionName);

        logger.debug(`🚀 [Executor] Step ${i + 1}/${plan.length}: ${step.agent} -> ${step.task}`);

        // Execute step and capture result
        const stepResult = await new Promise((resolve, reject) => {
          let stepText = '';

          agent.processStreaming(
            step.task,
            userInput,
            currentContext,
            conversationState,
            conversationHistory,
            // onChunk - always stream to user so they see progress
            (chunk) => {
              if (onChunk) {
                onChunk(chunk);
              }
              stepText += chunk;
            },
            // onComplete - capture the full result
            (result) => {
              resolve({
                text: stepText || result.text,
                visualElements: result.visualElements || [],
                actions: result.actions || [],
                nextSteps: result.nextSteps, // Preserve for agent handoffs
              });
            },
            // onError
            (error) => {
              logger.error(`❌ [Executor] Step ${i + 1} error:`, error);
              // Resolve with empty result to continue chain
              resolve({
                text: '',
                visualElements: [],
                actions: [],
              });
            }
          );
        });

        // Accumulate results from EVERY step (including this one)
        // This ensures completed steps are preserved even if we pause later
        allVisualElements.push(...stepResult.visualElements);
        allActions.push(...stepResult.actions);

        // Accumulate text from all completed steps
        if (stepResult.text) {
          finalText = finalText ? `${finalText}\n\n${stepResult.text}` : stepResult.text;
        }

        // Check if this step needs more info (has question but no visualElements)
        const hasQuestion = stepResult.text?.includes('?');
        const isComplete = Array.isArray(stepResult.visualElements) && stepResult.visualElements.length > 0;

        // PAUSE EXECUTION if step needs more info and there are more steps after this
        if (hasQuestion && !isComplete && !isLastStep) {
          const remainingSteps = plan.slice(i + 1);
          logger.debug(`⏸️ [Executor] Pausing - ${step.agent} needs more info. ${remainingSteps.length} steps remaining.`);

          if (onComplete) {
            onComplete({
              // Include ALL accumulated content, not just this step's
              text: finalText,
              visualElements: allVisualElements,
              actions: allActions,
              // Include metadata for CoreAgent to track pending steps
              _meta: {
                paused: true,
                currentAgent: step.agent,
                currentTask: step.task,
                pendingSteps: remainingSteps,
              }
            });
          }
          return; // Stop execution here - CoreAgent will resume later
        }

        // For nextSteps, use the last step's response
        if (isLastStep) {
          lastNextSteps = stepResult.nextSteps;
        }

        // Build context for next step with results from this step
        currentContext = this.buildStepContext(stepResult, currentContext);

      } catch (error) {
        logger.error(`❌ [Executor] Error in step ${i + 1}:`, error);
        // Continue to next step
      }
    }

    // Send final combined response
    if (onComplete) {
      onComplete({
        text: finalText,
        visualElements: allVisualElements,
        actions: allActions,
        nextSteps: lastNextSteps, // Pass through for agent handoffs
      });
    }
  }
}

export const executePlan = (...args) => {
  const engine = new ExecutionEngine();
  return engine.executePlan(...args);
};
