/**
 * ExecutionEngine.js - Runs the plan generated by the CoreAgent
 *
 * MULTI-STEP EXECUTION WITH PROGRESSIVE UPDATES
 * - Executes ALL steps in a plan sequentially
 * - Streams progress for each step ("Creating project... ✓ Done!")
 * - Passes context from step N to step N+1
 * - Accumulates visual elements and actions from all steps
 */

// Import all the specialized "worker" agents
import ProjectAgent from '../ProjectAgent';
import FinancialAgent from '../FinancialAgent';
import EstimateInvoiceAgent from '../EstimateInvoiceAgent';
import DocumentAgent from '../DocumentAgent';
import WorkersSchedulingAgent from '../WorkersSchedulingAgent';
import SettingsConfigAgent from '../SettingsConfigAgent';
import logger from '../../../utils/logger';
import i18n from '../../../i18n';

class ExecutionEngine {
  constructor() {
    // A registry of all available agents
    this.agents = {
      ProjectAgent: new ProjectAgent(),
      FinancialAgent: new FinancialAgent(),
      EstimateInvoiceAgent: new EstimateInvoiceAgent(),
      DocumentAgent: new DocumentAgent(),
      WorkersSchedulingAgent: new WorkersSchedulingAgent(),
      SettingsConfigAgent: new SettingsConfigAgent(),
    };
  }

  /**
   * Builds context for next step based on previous step's results
   * @param {object} previousResult - Result from previous step execution
   * @param {object} baseContext - Original context
   * @returns {object} - Enhanced context for next step
   */
  buildStepContext(previousResult, baseContext) {
    return {
      ...baseContext,
      previousStepResult: {
        text: previousResult.text,
        visualElements: previousResult.visualElements,
        actions: previousResult.actions,
        // Extract any created entities for reference
        createdProject: previousResult.visualElements?.find(v => v.type === 'ProjectCard')?.data,
        createdEstimate: previousResult.visualElements?.find(v => v.type === 'EstimateCard')?.data,
        createdInvoice: previousResult.visualElements?.find(v => v.type === 'InvoiceCard')?.data,
      }
    };
  }

  /**
   * Get a friendly status message for the UI based on agent and task
   * Uses i18n for translations
   */
  getStatusMessage(agent, task) {
    // Map agent/task to i18n keys
    const STATUS_KEYS = {
      // ==================== PROJECT AGENT ====================
      ProjectAgent: {
        start_project_creation: 'settingUpProject',
        continue_project_creation: 'finishingProject',
        update_project: 'updatingProject',
      },

      // ==================== WORKERS & SCHEDULING AGENT ====================
      WorkersSchedulingAgent: {
        query_workers: 'lookingUpWorker',
        manage_worker: 'updatingWorker',
        assign_worker: 'assigningWorker',
        track_time: 'pullingTimeRecords',
        edit_time_entry: 'correctingTimeEntry',
        manage_schedule_event: 'updatingCalendar',
        retrieve_schedule_events: 'checkingSchedule',
        manage_work_schedule: 'schedulingCrew',
        retrieve_photos: 'loadingPhotos',
        retrieve_daily_reports: 'pullingReports',
        manage_daily_report: 'savingReport',
        query_worker_payment: 'calculatingPay',
        manage_availability: 'checkingAvailability',
        manage_crew: 'organizingCrew',
        manage_shift_template: 'loadingTemplates',
        manage_breaks: 'recordingBreak',
        find_replacement: 'findingWorkers',
        analytics: 'analyzingData',
      },

      // ==================== ESTIMATE & INVOICE AGENT ====================
      EstimateInvoiceAgent: {
        create_estimate: 'buildingEstimate',
        create_invoice: 'generatingInvoice',
        update_estimate: 'revisingEstimate',
        find_estimates: 'searchingEstimates',
        find_invoices: 'lookingUpInvoices',
        send_estimate: 'preparingEstimate',
        create_project_from_estimate: 'convertingToProject',
      },

      // ==================== FINANCIAL AGENT ====================
      FinancialAgent: {
        record_transaction: 'recordingTransaction',
        answer_financial_question: 'crunchingNumbers',
        query_transactions: 'pullingTransactions',
        analyze_financials: 'analyzingFinances',
      },

      // ==================== DOCUMENT AGENT ====================
      DocumentAgent: {
        find_documents: 'searchingDocuments',
        find_project: 'searchingProject',
        update_project: 'updatingProject',
        delete_project: 'removingProject',
        answer_general_question: 'thinking',
        add_estimate_to_project: 'linkingEstimate',
        manage_estimate: 'updatingEstimate',
        manage_invoice: 'processingInvoice',
        manage_contract: 'updatingContract',
        search_documents: 'searchingDocuments',
        list_contract_documents: 'loadingContracts',
        upload_contract_document: 'uploadingDocument',
        send_contract_document: 'preparingContract',
      },

      // ==================== SETTINGS AGENT ====================
      SettingsConfigAgent: {
        query_settings: 'loadingSettings',
        manage_business_settings: 'updatingBusiness',
        manage_phase_templates: 'configuringTemplates',
        manage_service_catalog: 'updatingPrices',
        manage_profit_margins: 'adjustingMargins',
        manage_subcontractor_quotes: 'managingSubs',
        manage_invoice_template: 'customizingInvoice',
      },
    };

    const key = STATUS_KEYS[agent]?.[task] || 'workingOnIt';
    return i18n.t(`chat:status.${key}`);
  }

  /**
   * Get a friendly action name for progress updates (used in multi-step streaming)
   */
  getStepActionName(step) {
    return this.getStatusMessage(step.agent, step.task);
  }

  /**
   * Executes a plan and streams the response.
   * NOW SUPPORTS MULTI-STEP EXECUTION WITH PROGRESSIVE UPDATES
   *
   * @param {object} planObject - The plan from CoreAgent, e.g., { reasoning: '...', plan: [...] }.
   * @param {string} originalUserMessage - The original full user message.
   * @param {object} context - The full dynamic context.
   * @param {object} conversationState - The current conversation state.
   * @param {array} conversationHistory - The conversation history (messages).
   * @param {function} onChunk - Callback for streaming text chunks.
   * @param {function} onComplete - Callback for the final structured response.
   * @param {function} onError - Callback for errors.
   * @param {function} onStatusChange - Callback for updating status message (e.g., "Creating project...")
   */
  async executePlan(planObject, originalUserMessage, context, conversationState, conversationHistory, onChunk, onComplete, onError, onStatusChange) {
    const { plan } = planObject;
    logger.debug('🚀 [Executor] Starting execution of plan:', plan);

    if (!plan || plan.length === 0) {
      logger.warn('🚀 [Executor] Received an empty plan. Nothing to execute.');
      if (onComplete) onComplete({
        text: "Is there anything else I can help with?",
        visualElements: [],
        actions: [],
      });
      return;
    }

    // ⛔ SUPERVISOR SAFETY CHECK: Block restricted agents (backup check)
    const SUPERVISOR_RESTRICTED_AGENTS = ['ProjectAgent', 'EstimateInvoiceAgent'];
    if (context?.isSupervisorMode && plan?.length > 0) {
      const blockedStep = plan.find(step => SUPERVISOR_RESTRICTED_AGENTS.includes(step.agent));
      if (blockedStep) {
        logger.warn(`⛔ [Executor] Blocking ${blockedStep.agent} for supervisor`);
        if (onComplete) onComplete({
          text: `As a supervisor, I can't help with that action. Only your owner can create projects, estimates, and invoices.`,
          visualElements: [],
          actions: []
        });
        return;
      }
    }

    // SINGLE STEP - Use original fast path (no overhead)
    if (plan.length === 1) {
      const step = plan[0];
      const agent = this.agents[step.agent];

      if (!agent) {
        const errorMessage = `Agent "${step.agent}" not found.`;
        logger.error(`❌ [Executor] ${errorMessage}`);
        if (onError) onError(new Error(errorMessage));
        return;
      }

      try {
        const userInput = step.user_input === 'FULL_MESSAGE' ? originalUserMessage : step.user_input;

        // Update status message for this agent/task
        const statusMsg = this.getStatusMessage(step.agent, step.task);
        onStatusChange?.(statusMsg);

        logger.debug(`🚀 [Executor] Single step - delegating to ${step.agent} for task: ${step.task}`);
        await agent.processStreaming(
          step.task,
          userInput,
          context,
          conversationState,
          conversationHistory,
          onChunk,
          onComplete,
          onError
        );
      } catch (error) {
        logger.error(`❌ [Executor] Error during agent execution:`, error);
        if (onError) onError(error);
      }
      return;
    }

    // MULTI-STEP EXECUTION - PAUSE ON QUESTION (Manus-style)
    // If a step needs more info (asks question, no visualElements), pause and wait for user
    logger.debug(`🚀 [Executor] Multi-step execution: ${plan.length} steps`);

    // Accumulators for final response
    const allVisualElements = [];
    const allActions = [];
    let finalText = '';
    let lastNextSteps = null; // Track nextSteps from last step for handoffs
    let currentContext = context;

    // Track execution errors for debugging and user feedback
    const executionErrors = [];

    for (let i = 0; i < plan.length; i++) {
      const step = plan[i];
      const isLastStep = i === plan.length - 1;
      const agent = this.agents[step.agent];

      if (!agent) {
        const errorMessage = `Agent "${step.agent}" not found.`;
        logger.error(`❌ [Executor] ${errorMessage}`);
        executionErrors.push({ step: i + 1, agent: step.agent, error: errorMessage });
        // Continue to next step instead of failing entirely
        continue;
      }

      try {
        const userInput = step.user_input === 'FULL_MESSAGE' ? originalUserMessage : step.user_input;
        const actionName = this.getStepActionName(step);

        // Update status message for this step
        onStatusChange?.(actionName);

        logger.debug(`🚀 [Executor] Step ${i + 1}/${plan.length}: ${step.agent} -> ${step.task}`);

        // Execute step and capture result
        const stepResult = await new Promise((resolve, reject) => {
          let stepText = '';

          agent.processStreaming(
            step.task,
            userInput,
            currentContext,
            conversationState,
            conversationHistory,
            // onChunk - always stream to user so they see progress
            (chunk) => {
              if (onChunk) {
                onChunk(chunk);
              }
              stepText += chunk;
            },
            // onComplete - capture the full result
            (result) => {
              resolve({
                text: stepText || result.text,
                visualElements: result.visualElements || [],
                actions: result.actions || [],
                nextSteps: result.nextSteps, // Preserve for agent handoffs
              });
            },
            // onError - track error but continue execution
            (error) => {
              logger.error(`❌ [Executor] Step ${i + 1} error:`, error);
              executionErrors.push({ step: i + 1, agent: step.agent, task: step.task, error: error.message || 'Unknown error' });
              // Resolve with error indicator to continue chain
              resolve({
                text: `Step ${i + 1} encountered an issue.`,
                visualElements: [],
                actions: [],
                _stepError: true,
              });
            }
          );
        });

        // Accumulate results from EVERY step (including this one)
        // This ensures completed steps are preserved even if we pause later
        allVisualElements.push(...stepResult.visualElements);
        allActions.push(...stepResult.actions);

        // Accumulate text from all completed steps
        if (stepResult.text) {
          finalText = finalText ? `${finalText}\n\n${stepResult.text}` : stepResult.text;
        }

        // Check if this step needs more info (has question but no visualElements)
        const hasQuestion = stepResult.text?.includes('?');
        const isComplete = Array.isArray(stepResult.visualElements) && stepResult.visualElements.length > 0;

        // PAUSE EXECUTION if step needs more info and there are more steps after this
        if (hasQuestion && !isComplete && !isLastStep) {
          const remainingSteps = plan.slice(i + 1);
          logger.debug(`⏸️ [Executor] Pausing - ${step.agent} needs more info. ${remainingSteps.length} steps remaining.`);

          if (onComplete) {
            onComplete({
              // Include ALL accumulated content, not just this step's
              text: finalText,
              visualElements: allVisualElements,
              actions: allActions,
              // Include metadata for CoreAgent to track pending steps
              _meta: {
                paused: true,
                currentAgent: step.agent,
                currentTask: step.task,
                pendingSteps: remainingSteps,
                executionErrors: executionErrors.length > 0 ? executionErrors : undefined,
              }
            });
          }
          return; // Stop execution here - CoreAgent will resume later
        }

        // For nextSteps, use the last step's response
        if (isLastStep) {
          lastNextSteps = stepResult.nextSteps;
        }

        // Build context for next step with results from this step
        currentContext = this.buildStepContext(stepResult, currentContext);

      } catch (error) {
        logger.error(`❌ [Executor] Error in step ${i + 1}:`, error);
        executionErrors.push({ step: i + 1, agent: step.agent, task: step.task, error: error.message || 'Execution error' });
        // Continue to next step
      }
    }

    // Send final combined response
    if (onComplete) {
      onComplete({
        text: finalText,
        visualElements: allVisualElements,
        actions: allActions,
        nextSteps: lastNextSteps, // Pass through for agent handoffs
        // Include execution metadata for debugging and error awareness
        _meta: executionErrors.length > 0 ? {
          executionErrors,
          partialSuccess: finalText.length > 0 || allVisualElements.length > 0,
        } : undefined,
      });
    }
  }
}

export const executePlan = (...args) => {
  const engine = new ExecutionEngine();
  return engine.executePlan(...args);
};
