/**
 * Client portal coverage map — consumed by client-coverage.test.js.
 * Generated by the client-screen-instrument workflow (all 15 client screens had
 * 0 testIDs before this), filtered to screens reachable via stable nav for the
 * seeded QA client (qa.client.mike — Mike Johnson, single-project, linked to
 * "Johnson Kitchen Remodel" via project_clients).
 *
 * NOTE ON CLIENT DATA: every client screen reads through the backend
 * /api/portal/* API (NOT Supabase directly), and almost every endpoint is gated
 * by a client_portal_settings row. That row + realistic content (estimate→sent,
 * 1 pending change order, 3 documents, 3 selections, 2 weekly summaries, photos
 * on daily_reports, a conversation) were seeded for Johnson Kitchen so these
 * screens render real content instead of empty states.
 *
 * Two of the 15 instrumented screens are intentionally NOT in this list:
 *  - clientProjectDetail: only reachable for MULTI-project clients (the
 *    single-project dashboard renders inline content, no project card to tap).
 *    Covered separately. See QA-FINDINGS.
 *  - clientMessagesList: NOT registered in ClientMainNavigator — orphaned/
 *    unreachable screen (a real finding, reported, not driven here).
 */
/* eslint-disable */

module.exports = [
  // ── 5 client tabs ──
  {
    screenKey: 'clientDashboard',
    navSteps: [{ action: 'tap', id: 'clientTab.Home' }],
    assertTestIds: ['clientDashboard.headerTitle', 'clientDashboard.headerSubtitle'],
  },
  {
    // currentPhaseName + selectedDayDate are above the fold; allPhasesLabel sits
    // below the calendar (off-screen on load), so it's not used as an assert.
    screenKey: 'clientTimeline',
    navSteps: [{ action: 'tap', id: 'clientTab.Timeline' }],
    assertTestIds: ['clientTimeline.currentPhaseName', 'clientTimeline.selectedDayDate'],
  },
  {
    screenKey: 'clientDocumentsTab',
    navSteps: [{ action: 'tap', id: 'clientTab.Documents' }],
    assertTestIds: ['clientDocumentsTab.headerTitle', 'clientDocumentsTab.documentsSectionLabel'],
  },
  {
    screenKey: 'clientMoney',
    navSteps: [{ action: 'tap', id: 'clientTab.Money' }],
    assertTestIds: ['clientMoney.headerTitle', 'clientMoney.contractValue', 'clientMoney.remainingValue'],
  },
  {
    screenKey: 'clientMore',
    navSteps: [{ action: 'tap', id: 'clientTab.More' }],
    assertTestIds: ['clientMore.headerTitle', 'clientMore.DocumentsLabel'],
  },

  // ── Detail screens reached from the Home dashboard (single-project inline) ──
  {
    screenKey: 'clientInvoices',
    navSteps: [
      { action: 'tap', id: 'clientTab.Home' },
      { action: 'tap', id: 'clientDashboard.invoicesButton' },
    ],
    assertTestIds: ['clientInvoices.headerTitle', 'clientInvoices.invoiceNumber'],
  },
  {
    screenKey: 'clientMessages',
    navSteps: [
      { action: 'tap', id: 'clientTab.Home' },
      { action: 'tap', id: 'clientDashboard.messagesButton' },
    ],
    assertTestIds: ['clientMessages.headerTitle', 'clientMessages.projectName'],
  },

  // ── Detail screens reached from the More tab ──
  {
    screenKey: 'clientDocuments',
    navSteps: [
      { action: 'tap', id: 'clientTab.More' },
      { action: 'tap', id: 'clientMore.DocumentsButton' },
    ],
    assertTestIds: ['clientDocuments.headerTitle', 'clientDocuments.filterAllButton'],
  },
  {
    screenKey: 'clientSelections',
    navSteps: [
      { action: 'tap', id: 'clientTab.More' },
      { action: 'tap', id: 'clientMore.SelectionsButton' },
    ],
    assertTestIds: ['clientSelections.headerTitle', 'clientSelections.cardTitle.0'],
  },
  {
    screenKey: 'clientPhotos',
    navSteps: [
      { action: 'tap', id: 'clientTab.More' },
      { action: 'tap', id: 'clientMore.PhotosButton' },
    ],
    assertTestIds: ['clientPhotos.headerTitle', 'clientPhotos.headerCount'],
  },
  {
    screenKey: 'clientAISummaries',
    navSteps: [
      { action: 'tap', id: 'clientTab.More' },
      { action: 'tap', id: 'clientMore.AISummariesButton' },
    ],
    assertTestIds: ['clientAISummaries.headerTitle', 'clientAISummaries.aiBadgeText'],
  },

  // ── Detail screens reached from the Money tab ──
  // reviewChangeOrdersButton sits near the TOP of the Money screen (no scroll
  // needed), so this runs before the estimate test.
  {
    screenKey: 'clientChangeOrderDetail',
    navSteps: [
      { action: 'tap', id: 'clientTab.Money' },
      { action: 'tap', id: 'clientMoney.reviewChangeOrdersButton' },
    ],
    assertTestIds: ['clientChangeOrderDetail.headerTitle', 'clientChangeOrderDetail.title'],
  },
  // Kept LAST: this scrolls the Money tab to the bottom to reach the estimate
  // row, and that scroll position persists on the Money tab — running it last
  // means it can't push a later test's top-of-screen target off-screen.
  {
    screenKey: 'clientEstimateDetail',
    navSteps: [
      { action: 'tap', id: 'clientTab.Money' },
      // The estimates section sits below the budget/change-order/invoice cards,
      // so scroll the Money list down to the estimate row before tapping it.
      { action: 'scrollTo', id: 'clientMoney.viewEstimateButton', scrollViewId: 'clientMoney.scrollView' },
    ],
    assertTestIds: ['clientEstimateDetail.headerTitle', 'clientEstimateDetail.title'],
  },
];
