/**
 * Owner screen coverage map — consumed by owner-coverage.test.js.
 *
 * Each entry: how to reach an owner screen from the bottom tabs (navSteps),
 * 2-4 testIDs visible once it loads (assertTestIds, the hard check), and
 * safeTapTestIds — in-screen, non-destructive, non-navigating controls the
 * test taps best-effort to exercise the buttons. Generated by the
 * owner-screen-map workflow, every id grep-verified against source, nav paths
 * confirmed on the iPhone 17 Pro simulator.
 *
 * Wave 1 = screens reachable through stable, testID-anchored nav. The rest of
 * the financial cluster (TaxSummary / ARAging / ContractorPayments /
 * PayrollSummary / BankReconciliation / ClockOuts) is reachable only via
 * optional dashboard widgets or data-gated alerts — see e2e/README.md.
 */
/* eslint-disable */

module.exports = [
  // ── Bottom tabs (always reachable) ──
  {
    screenKey: 'ownerDashboard',
    navSteps: [{ action: 'tap', id: 'ownerTab.Home' }],
    assertTestIds: ['ownerDashboard.welcomeText', 'ownerDashboard.dateText', 'ownerDashboard.customizeButton'],
    safeTapTestIds: ['ownerDashboard.customizeButton', 'ownerDashboard.doneButton'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'work',
    navSteps: [{ action: 'tap', id: 'ownerTab.Projects' }],
    assertTestIds: ['work.title', 'work.projectsTab', 'work.servicesTab'],
    safeTapTestIds: ['work.servicesTab', 'work.projectsTab', 'work.filterButton'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerProjects',
    navSteps: [{ action: 'tap', id: 'ownerTab.Projects' }],
    assertTestIds: ['ownerProjects.sectionTitle', 'ownerProjects.firstRow', 'work.projectsTab'],
    safeTapTestIds: ['work.servicesTab', 'work.projectsTab'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerWorkers',
    navSteps: [{ action: 'tap', id: 'ownerTab.Workers' }],
    assertTestIds: ['ownerWorkers.scheduleTab', 'ownerWorkers.reportsTab', 'ownerWorkers.teamTab'],
    safeTapTestIds: ['ownerWorkers.reportsTab', 'ownerWorkers.teamTab', 'ownerWorkers.scheduleTab'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerSettings',
    navSteps: [{ action: 'tap', id: 'ownerTab.Settings' }],
    assertTestIds: ['ownerSettings.headerTitle', 'ownerSettings.scrollView'],
    safeTapTestIds: ['ownerSettings.aiPersonalityToggle'],
    reachableFromOwnerTabs: true,
  },

  // ── Project-scoped (Projects -> first project card) ──
  {
    screenKey: 'projectDetail',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'ownerProjects.firstRow' },
    ],
    assertTestIds: ['projectDetail.title', 'projectDetail.contractValue', 'projectDetail.incomeTile'],
    // (Functional value-check capability exists via `assertText`; the first
    // project's contract value was manually verified correct = $12,000, but exact
    // currency strings are device-locale-dependent so we don't hard-assert them
    // in CI. The create-project flow in owner-flows.test.js is the robust
    // functional proof — it round-trips form → DB.)
    safeTapTestIds: ['projectDetail.budgetBreakdownToggle'],
    reachableFromOwnerTabs: true,
  },
  // NOTE: ownerSelections (Material Selections) is reachable in principle via
  // projectDetail.materialSelectionsLink, but that link sits at the very bottom
  // of the project-detail scroll below an AuditTrail + a nested ScrollView,
  // which traps Detox's whileElement scroll. Left as a documented gap rather
  // than ship a flaky test. (See e2e/README.md.)

  {
    screenKey: 'projectDocuments',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'ownerProjects.firstRow' },
      { action: 'scrollTo', id: 'documentsCard.headerButton', scrollViewId: 'projectDetail.scrollView' },
    ],
    assertTestIds: ['projectDocuments.title', 'projectDocuments.searchInput'],
    safeTapTestIds: ['projectDocuments.filterChip.plan', 'projectDocuments.filterChip.contract'],
    reachableFromOwnerTabs: true,
  },

  // ── Settings sub-screens (Settings -> scroll -> item) ──
  {
    screenKey: 'clients',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.clientsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['clients.headerTitle', 'clients.headerCount'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'integrations',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.integrationsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['integrations.title'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'editBusinessInfo',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.editProfileButton', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['editBusinessInfo.title', 'editBusinessInfo.saveButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'estimatesDetail',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.estimatesItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['estimatesDetail.headerTitle', 'estimatesDetail.searchInput'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'invoicesDetail',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.invoicesItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['invoicesDetail.headerTitle', 'invoicesDetail.addInvoiceButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'contracts',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.contractsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['contracts.headerTitle', 'contracts.uploadButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'invoiceTemplate',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.invoiceTemplateItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['invoiceTemplate.headerTitle', 'invoiceTemplate.logoPicker'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'bankConnection',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.bankTransactionsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['bankConnection.headerTitle', 'bankConnection.connectBankButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'pictures',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.photosItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['pictures.headerTitle', 'pictures.filterLabel'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'notificationSettings',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.notificationsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['notificationSettings.headerTitle', 'notificationSettings.allowAllSwitch'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'changeLanguage',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.languageItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['changeLanguage.title', 'changeLanguage.saveButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'addService',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.addServiceItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['addService.headerTitle', 'addService.backButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'subscriptionSettings',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.subscriptionItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['subscriptionSettings.title', 'subscriptionSettings.planName'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Financial report (via the default PnL dashboard widget) ──
  {
    screenKey: 'financialReport',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
    ],
    assertTestIds: ['financialReport.title', 'financialReport.summaryRevenue', 'financialReport.summaryExpenses'],
    safeTapTestIds: ['financialReport.viewProject', 'financialReport.viewCompany'],
    reachableFromOwnerTabs: true,
  },

  // ── Workers tab detail screens (Team sub-tab -> first row) ──
  {
    screenKey: 'supervisorDetail',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Workers' },
      { action: 'tap', id: 'ownerWorkers.teamTab' },
      { action: 'scrollTo', id: 'ownerWorkers.supervisorRow.first', scrollViewId: 'ownerWorkers.scrollView' },
    ],
    assertTestIds: ['supervisorDetail.headerTitle', 'supervisorDetail.backButton'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'workerDetailHistory',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Workers' },
      { action: 'tap', id: 'ownerWorkers.teamTab' },
      { action: 'scrollTo', id: 'ownerWorkers.workerRow.first', scrollViewId: 'ownerWorkers.scrollView' },
    ],
    assertTestIds: ['workerDetailHistory.headerTitle', 'workerDetailHistory.workerName'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  // NOTE: subcontractorDetail is instrumented (subDetail.* + ownerWorkers.subRow.first)
  // and a sub_organization + sub_engagement are seeded for the QA owner, but the
  // Workers→Subcontractors list loads from the backend GET /api/subs, which the
  // release sim build's in-app fetch fails to resolve (it returns 200 via curl
  // and the URL is bundled, so this is a sim/backend-integration issue, not a
  // harness defect) — so the sub row never renders to tap. supervisorDetail and
  // workerDetailHistory use Supabase-direct queries and pass. See e2e/README.md.
  {
    screenKey: 'notifications',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'tap', id: 'ownerSettings.notificationBell' },
    ],
    assertTestIds: ['notifications.headerTitle'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Financial sub-reports (via the Financial Report "Reports & Tools" grid) ──
  {
    screenKey: 'arAging',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
      { action: 'scrollTo', id: 'financialReport.reportCard.ARAging', scrollViewId: 'financialReport.scrollView' },
    ],
    assertTestIds: ['arAging.title', 'arAging.totalOutstanding'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'taxSummary',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
      { action: 'scrollTo', id: 'financialReport.reportCard.TaxSummary', scrollViewId: 'financialReport.scrollView' },
    ],
    assertTestIds: ['taxSummary.grossRevenue', 'taxSummary.netProfit'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'payrollSummary',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
      { action: 'scrollTo', id: 'financialReport.reportCard.PayrollSummary', scrollViewId: 'financialReport.scrollView' },
    ],
    assertTestIds: ['payrollSummary.title', 'payrollSummary.totalGrossPay'],
    safeTapTestIds: ['payrollSummary.groupByProjectToggle'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'contractorPayments',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
      { action: 'scrollTo', id: 'financialReport.reportCard.TaxSummary', scrollViewId: 'financialReport.scrollView' },
      { action: 'scrollTo', id: 'taxSummary.seeAllContractorsButton', scrollViewId: 'taxSummary.scrollView' },
    ],
    assertTestIds: ['contractorPayments.title'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Create / builder forms (open the form, assert it renders; no submit) ──
  {
    screenKey: 'manualProjectCreate',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'work.addProjectButton' },
    ],
    assertTestIds: ['manualProjectCreate.headerTitle', 'manualProjectCreate.nameInput', 'manualProjectCreate.createButton'],
    safeTapTestIds: ['manualProjectCreate.section.client', 'manualProjectCreate.section.financial', 'manualProjectCreate.section.timeline'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'estimateBuilder',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.estimatesItem', scrollViewId: 'ownerSettings.scrollView' },
      { action: 'tap', id: 'estimatesDetail.addButton' },
    ],
    assertTestIds: ['estimateBuilder.headerTitle', 'estimateBuilder.statusPill'],
    safeTapTestIds: ['estimateBuilder.sectionHeader.lineItems', 'estimateBuilder.sectionHeader.pricing'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'invoiceBuilder',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.invoicesItem', scrollViewId: 'ownerSettings.scrollView' },
      { action: 'tap', id: 'invoicesDetail.addInvoiceButton' },
    ],
    assertTestIds: ['invoiceBuilder.headerTitle', 'invoiceBuilder.statusBadge'],
    safeTapTestIds: ['invoiceBuilder.section.lineItems', 'invoiceBuilder.section.pricing'],
    reachableFromOwnerTabs: true,
  },
];
