/**
 * Owner screen coverage map — consumed by owner-coverage.test.js.
 *
 * Each entry: how to reach an owner screen from the bottom tabs (navSteps),
 * 2-4 testIDs visible once it loads (assertTestIds, the hard check), and
 * safeTapTestIds — in-screen, non-destructive, non-navigating controls the
 * test taps best-effort to exercise the buttons. Generated by the
 * owner-screen-map workflow, every id grep-verified against source, nav paths
 * confirmed on the iPhone 17 Pro simulator.
 *
 * Wave 1 = screens reachable through stable, testID-anchored nav. The rest of
 * the financial cluster (TaxSummary / ARAging / ContractorPayments /
 * PayrollSummary / BankReconciliation / ClockOuts) is reachable only via
 * optional dashboard widgets or data-gated alerts — see e2e/README.md.
 */
/* eslint-disable */

module.exports = [
  // ── Bottom tabs (always reachable) ──
  {
    screenKey: 'ownerDashboard',
    navSteps: [{ action: 'tap', id: 'ownerTab.Home' }],
    assertTestIds: ['ownerDashboard.welcomeText', 'ownerDashboard.dateText', 'ownerDashboard.customizeButton'],
    safeTapTestIds: ['ownerDashboard.customizeButton', 'ownerDashboard.doneButton'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'work',
    navSteps: [{ action: 'tap', id: 'ownerTab.Projects' }],
    assertTestIds: ['work.title', 'work.projectsTab', 'work.servicesTab'],
    safeTapTestIds: ['work.servicesTab', 'work.projectsTab', 'work.filterButton'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerProjects',
    navSteps: [{ action: 'tap', id: 'ownerTab.Projects' }],
    assertTestIds: ['ownerProjects.sectionTitle', 'ownerProjects.firstRow', 'work.projectsTab'],
    safeTapTestIds: ['work.servicesTab', 'work.projectsTab'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerWorkers',
    navSteps: [{ action: 'tap', id: 'ownerTab.Workers' }],
    assertTestIds: ['ownerWorkers.scheduleTab', 'ownerWorkers.reportsTab', 'ownerWorkers.teamTab'],
    safeTapTestIds: ['ownerWorkers.reportsTab', 'ownerWorkers.teamTab', 'ownerWorkers.scheduleTab'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'ownerSettings',
    navSteps: [{ action: 'tap', id: 'ownerTab.Settings' }],
    assertTestIds: ['ownerSettings.headerTitle', 'ownerSettings.scrollView'],
    safeTapTestIds: ['ownerSettings.aiPersonalityToggle'],
    reachableFromOwnerTabs: true,
  },

  // ── Project-scoped (Projects -> first project card) ──
  {
    screenKey: 'projectDetail',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'ownerProjects.firstRow' },
    ],
    assertTestIds: ['projectDetail.title', 'projectDetail.contractValue', 'projectDetail.incomeTile'],
    safeTapTestIds: ['projectDetail.budgetBreakdownToggle'],
    reachableFromOwnerTabs: true,
  },
  // NOTE: ownerSelections (Material Selections) is reachable in principle via
  // projectDetail.materialSelectionsLink, but that link sits at the very bottom
  // of the project-detail scroll below an AuditTrail + a nested ScrollView,
  // which traps Detox's whileElement scroll. Left as a documented gap rather
  // than ship a flaky test. (See e2e/README.md.)

  {
    screenKey: 'projectDocuments',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'ownerProjects.firstRow' },
      { action: 'scrollTo', id: 'documentsCard.headerButton', scrollViewId: 'projectDetail.scrollView' },
    ],
    assertTestIds: ['projectDocuments.title', 'projectDocuments.searchInput'],
    safeTapTestIds: ['projectDocuments.filterChip.plan', 'projectDocuments.filterChip.contract'],
    reachableFromOwnerTabs: true,
  },

  // ── Settings sub-screens (Settings -> scroll -> item) ──
  {
    screenKey: 'clients',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.clientsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['clients.headerTitle', 'clients.headerCount'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'integrations',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.integrationsItem', scrollViewId: 'ownerSettings.scrollView' },
    ],
    assertTestIds: ['integrations.title'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Financial report (via the default PnL dashboard widget) ──
  {
    screenKey: 'financialReport',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Home' },
      { action: 'tap', id: 'ownerDashboard.widget.pnl' },
    ],
    assertTestIds: ['financialReport.title', 'financialReport.summaryRevenue', 'financialReport.summaryExpenses'],
    safeTapTestIds: ['financialReport.viewProject', 'financialReport.viewCompany'],
    reachableFromOwnerTabs: true,
  },

  // ── Create / builder forms (open the form, assert it renders; no submit) ──
  {
    screenKey: 'manualProjectCreate',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Projects' },
      { action: 'tap', id: 'work.addProjectButton' },
    ],
    assertTestIds: ['manualProjectCreate.headerTitle', 'manualProjectCreate.nameInput', 'manualProjectCreate.createButton'],
    safeTapTestIds: ['manualProjectCreate.section.client', 'manualProjectCreate.section.financial', 'manualProjectCreate.section.timeline'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'estimateBuilder',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.estimatesItem', scrollViewId: 'ownerSettings.scrollView' },
      { action: 'tap', id: 'estimatesDetail.addButton' },
    ],
    assertTestIds: ['estimateBuilder.headerTitle', 'estimateBuilder.statusPill'],
    safeTapTestIds: ['estimateBuilder.sectionHeader.lineItems', 'estimateBuilder.sectionHeader.pricing'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'invoiceBuilder',
    navSteps: [
      { action: 'tap', id: 'ownerTab.Settings' },
      { action: 'scrollTo', id: 'ownerSettings.invoicesItem', scrollViewId: 'ownerSettings.scrollView' },
      { action: 'tap', id: 'invoicesDetail.addInvoiceButton' },
    ],
    assertTestIds: ['invoiceBuilder.headerTitle', 'invoiceBuilder.statusBadge'],
    safeTapTestIds: ['invoiceBuilder.section.lineItems', 'invoiceBuilder.section.pricing'],
    reachableFromOwnerTabs: true,
  },
];
