/**
 * Worker portal coverage map — consumed by worker-coverage.test.js.
 * Generated by the worker-screen-instrument workflow (all 11 worker screens had
 * 0 testIDs before this), filtered to screens reachable via stable nav for the
 * seeded QA worker (qa.worker.maria, assigned to Johnson Kitchen + Maple Ave).
 */
/* eslint-disable */

const JOHNSON = '65c7375f-60bf-479a-9d99-e968026dbfdd';

module.exports = [
  // ── 3 worker tabs ──
  {
    screenKey: 'timeClock',
    navSteps: [{ action: 'tap', id: 'workerTab.TimeClock' }],
    assertTestIds: ['timeClock.headerTitle', 'timeClock.todayHoursValue'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'todaysWork',
    navSteps: [{ action: 'tap', id: 'workerTab.TodaysWork' }],
    assertTestIds: ['todaysWork.headerTitle', 'todaysWork.headerSubtitle'],
    safeTapTestIds: ['todaysWork.calendarToggleButton'],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'workerProjects',
    navSteps: [{ action: 'tap', id: 'workerTab.WorkerProjects' }],
    assertTestIds: ['workerProjects.headerTitle'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Project detail (WorkerProjects -> assigned project card) ──
  {
    screenKey: 'workerProjectDetail',
    navSteps: [
      { action: 'tap', id: 'workerTab.WorkerProjects' },
      { action: 'tap', id: `workerProjects.projectCard.${JOHNSON}` },
    ],
    assertTestIds: ['workerProjectDetail.headerTitle', 'workerProjectDetail.infoSectionTitle'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },

  // ── Forms reached from the Time Clock tab ──
  {
    screenKey: 'dailyReportForm',
    navSteps: [
      { action: 'tap', id: 'workerTab.TimeClock' },
      { action: 'tap', id: 'timeClock.dailyReportButton' },
    ],
    assertTestIds: ['dailyReportForm.headerTitle', 'dailyReportForm.projectSelectTitle'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
  {
    screenKey: 'expenseForm',
    navSteps: [
      { action: 'tap', id: 'workerTab.TimeClock' },
      { action: 'tap', id: 'timeClock.addExpenseButton' },
    ],
    assertTestIds: ['expenseForm.headerTitle', 'expenseForm.selectProjectTitle'],
    safeTapTestIds: [],
    reachableFromOwnerTabs: true,
  },
];
