-- Add phases, schedule, and scope columns to estimates table
-- This enables storing the full rich estimate structure generated by AI

-- Add phases column (stores phase breakdown with tasks)
ALTER TABLE estimates
ADD COLUMN IF NOT EXISTS phases JSONB DEFAULT '[]'::jsonb;

-- Add schedule column (stores timeline and phase schedule)
ALTER TABLE estimates
ADD COLUMN IF NOT EXISTS schedule JSONB DEFAULT '{}'::jsonb;

-- Add scope column (stores scope analysis)
ALTER TABLE estimates
ADD COLUMN IF NOT EXISTS scope JSONB DEFAULT '{}'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN estimates.phases IS 'Array of phases with tasks, durations, and budgets: [{name, plannedDays, budget, tasks: [{id, order, description, completed}]}]';
COMMENT ON COLUMN estimates.schedule IS 'Timeline data: {startDate, estimatedEndDate, phaseSchedule: [{phaseName, startDate, endDate}]}';
COMMENT ON COLUMN estimates.scope IS 'Scope analysis: {description, squareFootage, complexity}';
